### PR TITLE
initial commit for index.html

### PR DESCRIPTION
**Pull request by Rhowie86**
## changes
1) built html out from wireframe 
2) added flag images and made them links to coinciding page
3) added link in header for font family

## testing
1) serve branch with index.html
2) make sure index.html loads properly with correct alterations

### CODE REVIEW

**Comment by Resch17** [comment]
👍

**Comment by kohinrichs** [comment]
Is it worth capitalizing the country names in the alt text for the flags?

**Review by Rhowie86 — COMMENTED** [review]
Hey guys, resolved a merge conflict before approval.

**Comment by Rhowie86** [comment]
added rules requiring 2 approvals for merge

**Review by Resch17 — APPROVED** [review]
👍

**Review by Ni236630 — APPROVED** [review]
👍

**Pull request merged**
