### PR TITLE
added images/canada.png; added canada city, landmark, and citizen lists

### PR DESCRIPTION
**Pull request by Resch17**
## changes:
1) added canada.png to images/ directory
2) populated unordered lists of cities, landmarks, and citizens on canada.html with links to external sites for each

## testing:
1) serve branch and open canada.html in browser
2) verify that canada.png appears above canada headline
3) verify that lists populate with links to external sites for each list item

### CODE REVIEW

**Comment by Rhowie86** [comment]
👍

**Review by Rhowie86 — APPROVED** [review]
👍

**Comment by Rhowie86** [comment]
👍

**Review by Ni236630 — APPROVED** [review]
👍 

looks like we've gotta add the `@import "mainBody.css"`

**Pull request merged**
