### PR TITLE
initial commit for Japan

### PR DESCRIPTION
**Pull request by Rhowie86**
## Created Japan Page

1) added content for japan
2) couldn't decide on an image to use for the "country image" (looking for feedback)
3) created links for places to visit, landmarks to visit, and famous citizens.

## Testing

1) serve pages/japan.html
2) check for content updates (working images and links)
3) test links in the body (places, landmarks, citizens) to ensure all work

### CODE REVIEW

**Comment by Resch17** [comment]
The header on your third list still says "Notable Canadians", other than that it's good. If you fix that on another commit (and re-push the branch), I'll approve it. I don't think you have to cancel the PR, I think you can just add another commit and push it again.

As for the images, I like the one with the torii gates - it reminds me of Ghost of Tsushima!

**Review by Resch17 — APPROVED** [review]
👍

**Review by Ni236630 — APPROVED** [review]
looks good. i agree about the skyline.. looks like a solid choice for picture.

**Comment by christinaashworth** [comment]
👍

**Pull request merged**
