### PR TITLE
created footer.css; adjusted footer right side of view; added footer …

### PR DESCRIPTION
**Pull request by Ni236630**
…import to main.css

## changes 

1. created footer.css
2. flexed on the footer; row-reverse to shove copyright to the right
3. added import tag to main.css

## test

1. serve it up
2. make sure that the footer is now at right instead of left. 
3. with import tag it should be available on all webpages that have main.css linked.

### CODE REVIEW

**Comment by Resch17** [comment]
looks like you missed the semicolon after the import method in _main.css_. should be `@import "footer.css";`

also, the link tag to _main.css_ file on _China.html_ doesn't appear to be working. you may need to change the path to `/./styles/main.css`

**Comment by Ni236630** [comment]
> looks like you missed the semicolon after the import method in _main.css_. should be `@import "footer.css";`
> 
> also, the link tag to _main.css_ file on _China.html_ doesn't appear to be working. you may need to change the path to `/./styles/main.css`

fixed the `import` ; weird about the .css yours works, but as does the other ones on my screen. does japan's site also display incorrectly?

**Comment by Resch17** [comment]
yeah, looks like it works now! approval incoming

**Review by Resch17 — APPROVED** [review]
👍

**Review by Rhowie86 — APPROVED** [review]
🍨

**Pull request merged**
